### ISSUE TITLE
Add Travis CI to project

### ISSUE THREAD

**Issue by holyburger** [BME-MIT-IET/ontologiaicsoda-iet-2018#1]
Continuous integration service should be added to the project.

**Comment by mktiti** [comment]
Added travis configuration and ant 'test' target to use.

[Ant test target](https://github.com/BME-MIT-IET/ontologiaicsoda-iet-2018/commit/913a9464ef30d41eb38cc1e21936bf001f70a6b5)
[Travis configuration](https://github.com/BME-MIT-IET/ontologiaicsoda-iet-2018/commit/2c93b5a3cb84907875509996f391567efb6707c2)
