### ISSUE TITLE
Improve code coverage 

### ISSUE THREAD

**Issue by holyburger** [BME-MIT-IET/ontologiaicsoda-iet-2018#13]
First make an initial code coverage statistics, then improve it by adding more tests.

**Comment by holyburger** [comment]
Created wiki page for JaCoCo.

**Comment by KicsiMonkey** [comment]
https://github.com/BME-MIT-IET/ontologiaicsoda-iet-2018/commit/4639f98db529f7600439dd798925713461008b48
