### ISSUE TITLE
Analyze project with SonarCloud

### ISSUE THREAD

**Issue by holyburger** [BME-MIT-IET/ontologiaicsoda-iet-2018#2]
Add SonarCloud to the project, then analyze it.

**Comment by mktiti** [comment]
Migrated to maven build system for SonarCloud support

[Maven migration commit](https://github.com/BME-MIT-IET/ontologiaicsoda-iet-2018/commit/293c82578b3621adf7d41bac8d504069a7679a9d)

**Comment by KicsiMonkey** [comment]
Maven and SonarCloud both work, thanks!
