### ISSUE TITLE
Fix blocker bugs identified by SonarCloud

### ISSUE THREAD

**Issue by mktiti** [BME-MIT-IET/ontologiaicsoda-iet-2018#4]
Fix the current bugs from SonarCloud with 'Blocker' severity.

[Current Blocker bugs](https://sonarcloud.io/project/issues?id=ontologiai-csoda%3Acsv2rdf&resolved=false&severities=BLOCKER)

**Comment by holyburger** [comment]
1 blocker bug remained.

**Comment by holyburger** [comment]
Blocker bugs have been fixed.
